name: MCSkulls
version: '1.0-SNAPSHOT'
main: me.noname.mcskulls.Main
api-version: '1.15'
depend:
  - Vault
  - PlaceholderAPI
commands:
  czaszki:
permissions:
  skuls.admin:
    default: op
    description: admin command

